# Generated by Django 4.0.1 on 2022-04-29 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watch_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
